package com.hu.mapper;

import com.hu.model.PeActallot;
import java.util.List;

public interface PeActallotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actallot
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actallot
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    int insert(PeActallot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actallot
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    PeActallot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actallot
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    List<PeActallot> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actallot
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    int updateByPrimaryKey(PeActallot record);
}