package com.hu.mapper;

import com.hu.model.testUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface testUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testUser
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testUser
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    int insert(testUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testUser
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    testUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testUser
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    List<testUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testUser
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    int updateByPrimaryKey(testUser record);



     testUser selectByFilter(
                              @Param("username") String username,
                              @Param("userpass")String userpass);
}