package com.hu.model;

import java.util.Date;

public class PeActallot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.id
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.actid
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private Integer actid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.actname
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private String actname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.studentid
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private Integer studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.sysuserid
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private Integer sysuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.sysusername
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private String sysusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.acttype
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private Integer acttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.createTime
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.callTime
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private Date calltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.callStatus
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private Integer callstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.actCreater
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private Integer actcreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actallot.remark
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.id
     *
     * @return the value of actallot.id
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.id
     *
     * @param id the value for actallot.id
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.actid
     *
     * @return the value of actallot.actid
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public Integer getActid() {
        return actid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.actid
     *
     * @param actid the value for actallot.actid
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setActid(Integer actid) {
        this.actid = actid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.actname
     *
     * @return the value of actallot.actname
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public String getActname() {
        return actname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.actname
     *
     * @param actname the value for actallot.actname
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setActname(String actname) {
        this.actname = actname == null ? null : actname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.studentid
     *
     * @return the value of actallot.studentid
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.studentid
     *
     * @param studentid the value for actallot.studentid
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.sysuserid
     *
     * @return the value of actallot.sysuserid
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public Integer getSysuserid() {
        return sysuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.sysuserid
     *
     * @param sysuserid the value for actallot.sysuserid
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setSysuserid(Integer sysuserid) {
        this.sysuserid = sysuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.sysusername
     *
     * @return the value of actallot.sysusername
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public String getSysusername() {
        return sysusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.sysusername
     *
     * @param sysusername the value for actallot.sysusername
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setSysusername(String sysusername) {
        this.sysusername = sysusername == null ? null : sysusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.acttype
     *
     * @return the value of actallot.acttype
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public Integer getActtype() {
        return acttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.acttype
     *
     * @param acttype the value for actallot.acttype
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setActtype(Integer acttype) {
        this.acttype = acttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.createTime
     *
     * @return the value of actallot.createTime
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.createTime
     *
     * @param createtime the value for actallot.createTime
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.callTime
     *
     * @return the value of actallot.callTime
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public Date getCalltime() {
        return calltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.callTime
     *
     * @param calltime the value for actallot.callTime
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setCalltime(Date calltime) {
        this.calltime = calltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.callStatus
     *
     * @return the value of actallot.callStatus
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public Integer getCallstatus() {
        return callstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.callStatus
     *
     * @param callstatus the value for actallot.callStatus
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setCallstatus(Integer callstatus) {
        this.callstatus = callstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.actCreater
     *
     * @return the value of actallot.actCreater
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public Integer getActcreater() {
        return actcreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.actCreater
     *
     * @param actcreater the value for actallot.actCreater
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setActcreater(Integer actcreater) {
        this.actcreater = actcreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actallot.remark
     *
     * @return the value of actallot.remark
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actallot.remark
     *
     * @param remark the value for actallot.remark
     *
     * @mbggenerated Sun Jun 10 15:09:58 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}