package com.hu.model;

import java.util.Date;

public class sysuserstabDao {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.id
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.jobid
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private String jobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.looyuid
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private String looyuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.departmenid
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private Integer departmenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.username
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.realname
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.userphone
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.status
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.email
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.creator
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.creattime
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.modifier
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private Integer modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.modifytime
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.lastlogintime
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.lastloginip
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private String lastloginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.departmentcode
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private String departmentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.ip
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.calltype
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private Byte calltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuserstab.userpass
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    private String userpass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.id
     *
     * @return the value of sysuserstab.id
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.id
     *
     * @param id the value for sysuserstab.id
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.jobid
     *
     * @return the value of sysuserstab.jobid
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public String getJobid() {
        return jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.jobid
     *
     * @param jobid the value for sysuserstab.jobid
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setJobid(String jobid) {
        this.jobid = jobid == null ? null : jobid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.looyuid
     *
     * @return the value of sysuserstab.looyuid
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public String getLooyuid() {
        return looyuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.looyuid
     *
     * @param looyuid the value for sysuserstab.looyuid
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setLooyuid(String looyuid) {
        this.looyuid = looyuid == null ? null : looyuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.departmenid
     *
     * @return the value of sysuserstab.departmenid
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public Integer getDepartmenid() {
        return departmenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.departmenid
     *
     * @param departmenid the value for sysuserstab.departmenid
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setDepartmenid(Integer departmenid) {
        this.departmenid = departmenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.username
     *
     * @return the value of sysuserstab.username
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.username
     *
     * @param username the value for sysuserstab.username
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.realname
     *
     * @return the value of sysuserstab.realname
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.realname
     *
     * @param realname the value for sysuserstab.realname
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.userphone
     *
     * @return the value of sysuserstab.userphone
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.userphone
     *
     * @param userphone the value for sysuserstab.userphone
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.status
     *
     * @return the value of sysuserstab.status
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.status
     *
     * @param status the value for sysuserstab.status
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.email
     *
     * @return the value of sysuserstab.email
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.email
     *
     * @param email the value for sysuserstab.email
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.creator
     *
     * @return the value of sysuserstab.creator
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.creator
     *
     * @param creator the value for sysuserstab.creator
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.creattime
     *
     * @return the value of sysuserstab.creattime
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.creattime
     *
     * @param creattime the value for sysuserstab.creattime
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.modifier
     *
     * @return the value of sysuserstab.modifier
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.modifier
     *
     * @param modifier the value for sysuserstab.modifier
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.modifytime
     *
     * @return the value of sysuserstab.modifytime
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.modifytime
     *
     * @param modifytime the value for sysuserstab.modifytime
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.lastlogintime
     *
     * @return the value of sysuserstab.lastlogintime
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.lastlogintime
     *
     * @param lastlogintime the value for sysuserstab.lastlogintime
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.lastloginip
     *
     * @return the value of sysuserstab.lastloginip
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public String getLastloginip() {
        return lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.lastloginip
     *
     * @param lastloginip the value for sysuserstab.lastloginip
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setLastloginip(String lastloginip) {
        this.lastloginip = lastloginip == null ? null : lastloginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.departmentcode
     *
     * @return the value of sysuserstab.departmentcode
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public String getDepartmentcode() {
        return departmentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.departmentcode
     *
     * @param departmentcode the value for sysuserstab.departmentcode
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setDepartmentcode(String departmentcode) {
        this.departmentcode = departmentcode == null ? null : departmentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.ip
     *
     * @return the value of sysuserstab.ip
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.ip
     *
     * @param ip the value for sysuserstab.ip
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.calltype
     *
     * @return the value of sysuserstab.calltype
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public Byte getCalltype() {
        return calltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.calltype
     *
     * @param calltype the value for sysuserstab.calltype
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setCalltype(Byte calltype) {
        this.calltype = calltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuserstab.userpass
     *
     * @return the value of sysuserstab.userpass
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public String getUserpass() {
        return userpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuserstab.userpass
     *
     * @param userpass the value for sysuserstab.userpass
     *
     * @mbggenerated Wed Jun 13 00:32:04 CST 2018
     */
    public void setUserpass(String userpass) {
        this.userpass = userpass == null ? null : userpass.trim();
    }
}