package com.hu.model;

public class testUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testUser.id
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testUser.username
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testUser.userpass
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    private String userpass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testUser.id
     *
     * @return the value of testUser.id
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testUser.id
     *
     * @param id the value for testUser.id
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testUser.username
     *
     * @return the value of testUser.username
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testUser.username
     *
     * @param username the value for testUser.username
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testUser.userpass
     *
     * @return the value of testUser.userpass
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    public String getUserpass() {
        return userpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testUser.userpass
     *
     * @param userpass the value for testUser.userpass
     *
     * @mbggenerated Wed Jun 20 21:41:11 CST 2018
     */
    public void setUserpass(String userpass) {
        this.userpass = userpass == null ? null : userpass.trim();
    }
}